name: Node.js Package

on:
    push:
        branches:
            - "*"
jobs:
    publish-gpr:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: write
        steps:
            - uses: actions/checkout@v2

            - run: |
                  echo "Branch name ${GITHUB_REF##*/}"
            - name: Read version file
              id: set_var
              run: |
                  content=`cat ./package.json`
                  # the following lines are only required for multi line json
                  content="${content//'%'/'%25'}"
                  content="${content//$'\n'/'%0A'}"
                  content="${content//$'\r'/'%0D'}"
                  # end of optional handling for multi line json
                  echo "::set-output name=packageJson::$content"
            - run: |
                  echo "Current version: ${{fromJson(steps.set_var.outputs.packageJson).version}} "
            - name: Increase version
              id: bump_version
              uses: christian-draeger/increment-semantic-version@1.0.2
              with:
                  current-version: ${{fromJson(steps.set_var.outputs.packageJson).version}}
                  version-fragment: "bug"

            - run: |
                  echo "New version: ${{ steps.bump_version.outputs.next-version }}"
            - name: Update version in package.json
              uses: jossef/action-set-json-field@v1
              with:
                  file: package.json
                  field: version
                  value: ${{ steps.bump_version.outputs.next-version }}
            - name: Commit package.json
              run: |
                  git config --global user.name 'github-actions'
                  git config --global user.email 'github-actions@github.com'
                  git commit -am "Automated version to ${{ steps.bump_version.outputs.next-version }}"
                  git push
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
            - run: npm install
            - run: npm publish --tag ${GITHUB_REF##*/}
              env:
                  NODE_AUTH_TOKEN: "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"
